const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{物理: 0},
	{タイル状の背景: 0},
	{"ドラッグ＆ドロップ": 0},
	{スプライト: 0},
	{スプライト2: 0},
	{スプライト3: 0},
	{タッチ: 0},
	{マウス: 0},
	{スプライト4: 0},
	{スプライト5: 0},
	{タイル状の背景2: 0},
	{回転: 0},
	{スプライト6: 0},
	{キーボード: 0},
	{ボタン: 0},
	{テキスト: 0},
	{スプライト7: 0},
	{音声: 0},
	{変数1: 0}
];

self.InstanceType = {
	タイル状の背景: class extends self.ITiledBackgroundInstance {},
	スプライト: class extends self.ISpriteInstance {},
	スプライト2: class extends self.ISpriteInstance {},
	スプライト3: class extends self.ISpriteInstance {},
	タッチ: class extends self.IInstance {},
	マウス: class extends self.IInstance {},
	スプライト4: class extends self.ISpriteInstance {},
	スプライト5: class extends self.ISpriteInstance {},
	タイル状の背景2: class extends self.ITiledBackgroundInstance {},
	スプライト6: class extends self.ISpriteInstance {},
	キーボード: class extends self.IInstance {},
	ボタン: class extends self.IButtonInstance {},
	テキスト: class extends self.ITextInstance {},
	スプライト7: class extends self.ISpriteInstance {},
	音声: class extends self.IInstance {}
}